include: 'package:effective_dart/analysis_options.yaml'

analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    argument_type_not_assignable: error
    dead_code: info

linter:
  rules:
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    annotate_overrides: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    avoid_positional_boolean_parameters: false
    avoid_catches_without_on_clauses: false